import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ApolloClient,
  gql,
  HttpLink,
  InMemoryCache,
  ApolloProvider,
} from "@apollo/client";

const client = new ApolloClient({
  link: new HttpLink({
    uri: "http:/localhost:4000",
  }),
  cache: new InMemoryCache(),
});

const query = gql`
  query example($email: String!, $password: String!) {
    loginUser(email: $email, password: $password) {
      ... on UserSuccess {
        token
      }
      ... on Error {
        message
      }
    }
  }
`;

client.query({ query }).then((res) => {
  console.log(res.data);
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <body className={inter.className}>{children}</body>
      </ApolloProvider>
    </html>
  );
}
